// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnica.Context;

#nullable disable

namespace PruebaTecnica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240327180248_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaTecnica.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("TB_Cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Lulusis",
                            CUIT = "20-41936341-4",
                            Domicilio = "Calle Sata Catalina 3331",
                            Email = "mauricio.lulusis99@gmail.com",
                            FechaNacimiento = new DateTime(1999, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Mauricio Nicolás",
                            TelefonoCelular = "3764160290"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Lopez",
                            CUIT = "20-45935312-4",
                            Domicilio = "Itaembe Mini 223",
                            Email = "nicolas.sebastian@hotmail.com",
                            FechaNacimiento = new DateTime(2004, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nicolas Sebastian",
                            TelefonoCelular = "376180269"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Perez",
                            CUIT = "20-43567034-4",
                            Domicilio = "Rivadavia 2332",
                            Email = "sebasRodrigo@gmail.com",
                            FechaNacimiento = new DateTime(2006, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Lucas Rodrigo",
                            TelefonoCelular = "3764120590"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Correa",
                            CUIT = "24-24686668-9",
                            Domicilio = "Santa Fe 2233",
                            Email = "misamores801@gmail.com",
                            FechaNacimiento = new DateTime(1970, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Miriam Cristina",
                            TelefonoCelular = "3764178907"
                        },
                        new
                        {
                            Id = 5,
                            Apellidos = "Correa",
                            CUIT = "24-37905890-9",
                            Domicilio = "Centanerio y Monteagudo 2222",
                            Email = "martincorrea899012@gmail.com",
                            FechaNacimiento = new DateTime(1970, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Martin ",
                            TelefonoCelular = "3764848435"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
